//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Main.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_PROCESS_DIALOG              130
#define IDD_DRIVER_DIALOG               131
#define IDD_PROCESS_INFO_DIALOG         132
#define IDD_THREAD_DIALOG               133
#define IDD_VAD_DIALOG                  134
#define IDD_MODULE_DIALOG               135
#define IDD_MEMORY_DIALOG               136
#define IDD_HANDLE_DIALOG               137
#define IDR_MENU1                       138
#define IDD_TOKEN_DIALOG                138
#define IDR_MENU2                       139
#define IDR_MENU3                       140
#define IDD_CHANGE_MEMORY_DIALOG        143
#define IDD_VAD_PROTECTION_DLG          144
#define IDD_DIALOG1                     147
#define IDD_CALL_DIALOG                 149
#define IDD_EIP_CALL_DIALOG             150
#define IDD_APC_CALL_DIALOG             151
#define IDD_EXTERN_DIALOG               152
#define IDD_HWND_DIALOG                 153
#define IDD_HOOK_DIALOG                 154
#define IDD_DRIVER_DIALOG1              155
#define IDD_CALLBACK_DIALOG             155
#define IDC_MAIN_TAB                    1000
#define IDC_PROCESS_LIST                1008
#define IDC_PROCESSHOOK_LIST            1009
#define IDC_ENUMPROCESS_LIST            1009
#define IDC_DRIVER_LIST                 1010
#define IDC_SHOW_TEXT                   1013
#define IDC_PROCESS_INFO_TAB            1014
#define IDC_THREAD_LIST                 1015
#define IDC_VAD_LIST                    1016
#define IDC_PROCESS_TEXT                1017
#define IDC_HANLE_LIST                  1018
#define IDC_MEMORY_LIST                 1019
#define IDC_MODULE_LIST                 1020
#define IDC_CHECK1                      1021
#define IDC_CHECK_CLEAR1                1021
#define IDC_CHECK_DLL                   1021
#define IDC_CHECK_ENABLE                1021
#define IDC_CHECK2                      1022
#define IDC_CHECK_ENCLAVE               1022
#define IDC_TOKEN_LIST                  1023
#define IDC_CHECK_ERW                   1023
#define IDC_COMBO1                      1025
#define IDC_COMBO_TYPE                  1025
#define IDC_COMBO_PROTECTION            1026
#define IDC_CB_VAD                      1030
#define IDOK_OK                         1031
#define IDCANCEL_OK                     1032
#define ID_QUXIAO                       1032
#define IDC_PROTECTION_COMBO            1035
#define IDC_EDIT_ADDRESS                1036
#define IDC_EDIT_SIZE                   1037
#define IDC_EDIT_CALL                   1037
#define IDC_EDIT_ARG                    1038
#define IDC_EDIT_CALL_EIP               1039
#define IDC_EDIT_ARG_EIP                1040
#define IDC_EDIT_CALL_APC               1041
#define IDC_EDIT_ARG_APC                1042
#define IDC_BUTTON_GETPATH              1045
#define IDC_EDIT_PROCESS                1046
#define IDC_EDIT_DLL                    1047
#define IDC_BUTTON_PROCESS              1048
#define IDC_BUTTON_DLL                  1049
#define IDC_BUTTON_START                1050
#define IDC_WND_LIST                    1051
#define IDC_PROCESSHOOK2_LIST           1052
#define IDC_CHECK_HIDE                  1053
#define IDC_CALLBACK_LIST               1054
#define ID_HELP_AA                      32774
#define ID_PROCESSDLG_REFRESH           32775
#define ID_Menu                         32776
#define ID_Menu32777                    32777
#define ID_HELP_MOUDLE                  32778
#define ID_HELP_THREAD                  32779
#define ID_PROCESSDLG_SHOW_ALL_INFO     32780
#define ID_HANDLEDLG_REFRESH            32781
#define ID_HADN_SHOW_ALL_INFO           32782
#define ID_HANDLEDLG_SHOW               32783
#define ID_HANDLEDLG_3                  32784
#define ID_MEMORYDLG_REFRESH            32785
#define ID_MEMORY_1                     32786
#define ID_MEMORY_2                     32787
#define ID_MEMORY_3                     32788
#define ID_SUSPROCESS_                  32789
#define ID_Menu32790                    32790
#define ID_RESUME                       32791
#define ID_SUSPROCESS                   32792
#define ID_RESUME_PROCESS               32793
#define ID_RESUSEPROCESS                32794
#define ID_LOCATION_EXPLORER            32795
#define ID_COPY_PROCESS_NAME            32796
#define ID_COPY_PROCESS_PATH            32797
#define ID_KILL_PROCESS                 32798
#define ID_SUSPEND_THREAD               32799
#define ID_RESUME_THREAD                32800
#define ID_KILL_THREAD                  32801
#define ID_EXPORT_EXCEL                 32802
#define ID_EXPORT_TEXT                  32803
#define ID_FREE_DLL                     32804
#define ID_COPY_MODULE                  32805
#define ID_HIDE_MODULE                  32806
#define ID_DUMP_MEMORY                  32807
#define ID_CHANGE_MEMORYPROTECTION      32808
#define ID_CHANGE_VAD_PROTECTION        32809
#define ID_ALLOCATE_MEMORY              32810
#define ID_FREE_MEMORY                  32811
#define ID_MDL_WRITE_MEMORY             32812
#define ID_REMOTE_CALL                  32813
#define ID_APC_CALL                     32814
#define ID_RESFRESH                     32815
#define ID_CHECK_HOOK                   32816
#define ID_UNLOAD_DRIVER                32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
